### ISSUE TITLE
[Icon change needed] Icon is too simillar to Synology Chat

### ISSUE THREAD

**Issue by cyb3rko** [theolm/WhatsAppNoContact#36]
### Steps to reproduce

Not really a bug, but an issue.

1. Open the app menu of your phone.
2. Search for "Chat".

### Expected behavior

Listed apps should be distinguishable.

### Actual behavior

The app "Synology Chat" (https://play.google.com/store/apps/details?id=com.synology.dschat) does have the same name as your application, same colors and similar icon.

I would recommend to make the app more distinguishable.

### App version

v0.8.2

### Device

Google Pixel 7 Pro - Android 14

### Other details

<img src="https://github.com/user-attachments/assets/0a76b29e-d89a-4d46-8d1e-096add4806c0" width=300>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version.
- [X] I will fill out all of the requested information in this form.

**Comment by theolm** [comment]
I can see the problem here, the similarity, although accidental, exists. Unfortunately I'm not a designer so I don't have much ability to change the icon beyond what has already been changed. What I can do is change the title, but I believe that this is not the ideal solution.

I'll leave this issue open, maybe someone will pick it up to change the icon. Otherwise I'll work on it myself.

**Comment by RAHUL12348697695848579** [comment]
Hey I can design a logo please let me know how you would like it so I can make one

**Comment by theolm** [comment]
Hey, @RAHUL12348697695848579

I have no idea. you can suggest whatever you want,  I just have a few requirements.

1. It needs to be simple and somehow remind that, in the end, it will open WhatsApp
2. It needs to follow the latest [guidelines](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) for icons (adaptative icons, monochromatic, etc)

Thanks for taking this issue.

Thanks

**Comment by RAHUL12348697695848579** [comment]
And BTW I am not familiar with adaptive icon but I try my best

**Comment by RAHUL12348697695848579** [comment]
well guys i need a vote
![Untitled-1](https://github.com/user-attachments/assets/e9509a2b-da03-4474-984f-ac68e74713a1)

**Comment by JonnyTech** [comment]
I don't think you are allowed to use the WhatsApp icon within your one, it is probably trademarked and available only for official partners.

**Comment by theolm** [comment]
@RAHUL12348697695848579 Jonny is right, we can't use whatsapp icon. Besides there is too much information in your suggestion. I think it needs to be simple since this icon will be show in small devices as well.

Here is a codelab that can help you
https://codelabs.developers.google.com/design-android-launcher#0


I would try to use just a chat balloon with small modifications. I do prefer simple icons like this one

![Screenshot 2024-10-18 at 11 33 30 AM](https://github.com/user-attachments/assets/cfd9d8a1-d86f-4711-9aa8-ded156e0e801)

**Comment by RAHUL12348697695848579** [comment]
![image](https://github.com/user-attachments/assets/c1e0f3f5-89f3-414a-9696-30b37373fa52)
how about this

**Comment by RAHUL12348697695848579** [comment]
how about a chat bubble with a number to make it a little different

**Comment by RAHUL12348697695848579** [comment]
how is this looking?
![image](https://github.com/user-attachments/assets/78f525f2-b947-46a6-baf6-ea2e74ece08a)

**Comment by JonnyTech** [comment]
Nice, but it makes it look like this a proper chat app rather than an app that links to a chat app (sorry, that was a lot of "app"s!).

**Comment by RAHUL12348697695848579** [comment]
Lol it's kinda tough as you know there aren't any good chat bubble design that have that kinda notice but I see what I can do

**Comment by RAHUL12348697695848579** [comment]
![image](https://github.com/user-attachments/assets/a25977c9-04ed-4a8f-9ef6-7b19923be5b1)
how about i add this

**Comment by RAHUL12348697695848579** [comment]
![image](https://github.com/user-attachments/assets/2266c48e-8a38-4091-90de-22b5874dcb80)
how about this
i can remove the dot if it looks werid

**Comment by RAHUL12348697695848579** [comment]
high res vector ver 
![image](https://github.com/user-attachments/assets/00f2339f-bc92-4e71-bd2f-c32d9b3ecf92)

**Comment by theolm** [comment]
I like the idea of using a chat bubble with a chain (link) inside, but I think the icon itself is not following the guidelines. 

What if you take the existing icon and replace the 3 dots with a link?

**Comment by RAHUL12348697695848579** [comment]
I think you should proceed I give you the svg file

**Comment by RAHUL12348697695848579** [comment]
https://file.io/onzjJTq1fCJ6

**Comment by RAHUL12348697695848579** [comment]
wait do you mean like this?
![image](https://github.com/user-attachments/assets/def2bcd3-1ecf-410d-9f1a-c8f3151a197e)

**Comment by theolm** [comment]
Yes, so far I think this is our best choice.

Do you have any other ideas? Something that indicates that this will be passed/moved to WhatsApp. Maybe there will be some arrows inside the balloon. IDK haha

**Comment by RAHUL12348697695848579** [comment]
Hmm I mean I could make it a little different and use WhatsApp colour theme to make it that it goes to WhatsApp maybe

**Comment by shuvashish76** [comment]
I think instead of link icon launch icon would be nice.
I've tried to make an icon
![image](https://github.com/user-attachments/assets/f9302c2b-fd75-4b13-906a-54d8d031bf5a)

The svg file you can download from here : https://openclipart.org/detail/349889/chat-icon (Openclipart designs are under [Creative Commons Zero 1.0 Public Domain License](http://creativecommons.org/publicdomain/zero/1.0/))

Let me know if you like it or need some changes.

**Comment by shuvashish76** [comment]
Another try with rocket representing the user will open with whats app. Here I kept the 3dots for symbolism

![image](https://github.com/user-attachments/assets/a93d1293-5e18-4c6e-9df4-51e8fd0e0c83)

Source: https://openclipart.org/detail/349890/rocket-chat-icon

**Comment by RAHUL12348697695848579** [comment]
@theolm may I have your comment

**Comment by theolm** [comment]
As I said before, the icon needs to follow the Android guidelines for icons and also must be an adaptive icon with monochrome theme support. Neither of the suggestions are following my recommendations.

I created a new icon based on your idea using the chain to represent the link between the two apps.
I'll push the changes soon and I'll also give you the credits in the release.
